# Generated by Django 4.0.4 on 2022-04-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biz_Haqimizda_asosiy_rasm_matnlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavxa', models.CharField(max_length=40, verbose_name='Sarlavxa')),
                ('text', models.CharField(max_length=40, verbose_name='Matn')),
                ('izoh1', models.TextField(verbose_name='Izoh')),
                ('izoh2', models.TextField(verbose_name='Izoh')),
            ],
            options={
                'verbose_name_plural': '04_Biz haqimizda asosiy rasm matnlari',
            },
        ),
        migrations.CreateModel(
            name='Biz_Haqimizda_asosiy_rasmlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm_521x651', models.ImageField(upload_to='about3/')),
                ('rasm2_250x250', models.ImageField(upload_to='about3/')),
                ('rasm3_250x250', models.ImageField(upload_to='about3/')),
                ('rasm4_250x250', models.ImageField(upload_to='about3/')),
            ],
            options={
                'verbose_name_plural': '03_Biz haqimizda asosiy rasmlari',
            },
        ),
        migrations.CreateModel(
            name='Biz_Haqimizda_background_tagi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40, verbose_name='Matn')),
                ('izoh', models.TextField(verbose_name='Izoh')),
            ],
            options={
                'verbose_name_plural': '01_Biz haqimizda background tagi',
            },
        ),
        migrations.CreateModel(
            name='Biz_Haqimizda_background_tagi2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='about2/')),
                ('text', models.CharField(max_length=40, verbose_name='Matn')),
                ('izoh', models.TextField(verbose_name='Izoh')),
            ],
            options={
                'verbose_name_plural': '02_Biz haqimizda background tagi2',
            },
        ),
        migrations.CreateModel(
            name='Biz_Haqimizda_pastdagi_asosiy_rasmlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm_305x350', models.ImageField(upload_to='about6/')),
                ('matn', models.CharField(max_length=30)),
                ('izoh', models.TextField(max_length=200)),
                ('telegram_url', models.CharField(max_length=150)),
                ('instagram_url', models.CharField(max_length=150)),
                ('facebook_url', models.CharField(max_length=150)),
                ('youtube_url', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': '07_Biz haqimizda pastdagi asosiy rasmlar',
            },
        ),
        migrations.CreateModel(
            name='Biz_Haqimizda_pastdagi_asosiy_rasmlar_matni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asosiy_matn', models.CharField(max_length=20)),
                ('asosiy_izoh', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': '06_Biz haqimizda pastdagi asosiy rasmlar matni',
            },
        ),
        migrations.CreateModel(
            name='Biz_Haqimizda_statiskalar_tagi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavxa', models.CharField(max_length=40, verbose_name='Sarlavxa')),
                ('matn', models.CharField(max_length=40, verbose_name='Matn')),
                ('rasm_84x100', models.ImageField(upload_to='about5/')),
                ('rasm_matni', models.CharField(max_length=40, verbose_name='Matn')),
                ('rasm_izohi', models.TextField(verbose_name='Izoh')),
            ],
            options={
                'verbose_name_plural': '05_Biz haqimizda statiskalar tagi',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=15)),
                ('Company_phone', models.CharField(max_length=15)),
                ('Company_secondPhone', models.CharField(blank=True, max_length=15)),
                ('Logo', models.ImageField(blank=True, upload_to='logo', verbose_name="LOGO : 178x117 o'lcham tavsiya etiladi")),
                ('info', models.TextField(verbose_name="Kompaniya haqida ma'lumot")),
            ],
            options={
                'verbose_name_plural': "Konpaniya ma'lumotlari va u haqida",
            },
        ),
        migrations.CreateModel(
            name='Mainpage_1section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=70, verbose_name='Title')),
                ('desc', models.TextField(verbose_name="Sarlavha ostidagi text '160 ta letter tavsiya etiladi")),
                ('desc_last', models.TextField(verbose_name="Sarlavha ostidagi text '160 ta letter tavsiya etiladi_davomi")),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='#1 bilan yozilgan text')),
                ('imgbig', models.ImageField(upload_to='img', verbose_name="Asosiy surat katta (PNG format va 521x651 o'lchamlar tavsiya etiladi)")),
                ('img3', models.ImageField(upload_to='img', verbose_name="Yordamchi suratlar3 (PNG format va 250x250 o'lchamlar tavsiya etiladi)")),
                ('img2', models.ImageField(upload_to='img', verbose_name="Yordamchi suratlar2 (PNG format va 232x232 o'lchamlar tavsiya etiladi)")),
            ],
            options={
                'verbose_name_plural': '01_Bosh sahifa 1-section',
            },
        ),
        migrations.CreateModel(
            name='Section3s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=70, verbose_name='3- section krish yozuvi')),
                ('title', models.CharField(max_length=70, verbose_name='3- section krish yozuvi osti')),
                ('cardicon1', models.ImageField(blank=True, upload_to='icon')),
                ('cardicon2', models.ImageField(blank=True, upload_to='icon')),
                ('titlecard1', models.CharField(max_length=70, verbose_name='1- card sarlavhasi')),
                ('desccard1', models.CharField(max_length=70, verbose_name='1- card matni')),
                ('titlecard2', models.CharField(max_length=70, verbose_name='2- card sarlavhasi')),
                ('desccard2', models.CharField(max_length=70, verbose_name='2- card matni')),
            ],
            options={
                'verbose_name_plural': "<Bosh sahifa> 3- Section ma'lumotlari ",
            },
        ),
        migrations.CreateModel(
            name='Sectioninfor4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=100)),
                ('sarlavha_tagi', models.CharField(max_length=100)),
                ('icon1', models.ImageField(blank=True, upload_to='icon')),
                ('titlecard1', models.CharField(max_length=70, verbose_name='1-card sarlavhasi')),
                ('desccard1', models.CharField(max_length=70, verbose_name='1-card matni')),
                ('icon2', models.ImageField(blank=True, upload_to='icon')),
                ('titlecard2', models.CharField(max_length=70, verbose_name='2-card sarlavhasi')),
                ('desccard2', models.CharField(max_length=70, verbose_name='2-card matni')),
                ('icon3', models.ImageField(blank=True, upload_to='icon')),
                ('titlecard3', models.CharField(max_length=70, verbose_name='3-card sarlavhasi')),
                ('desccard3', models.CharField(max_length=70, verbose_name='3-card matni')),
                ('icon4', models.ImageField(blank=True, upload_to='icon')),
                ('titlecard4', models.CharField(max_length=70, verbose_name='4-card sarlavhasi')),
                ('desccard4', models.CharField(max_length=70, verbose_name='4-card matni')),
                ('icon5', models.ImageField(blank=True, upload_to='icon')),
                ('titlecard5', models.CharField(max_length=70, verbose_name='5-card sarlavhasi')),
                ('desccard5', models.CharField(max_length=70, verbose_name='5-card matni')),
            ],
        ),
        migrations.CreateModel(
            name='Slide2ensectionCarusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': "<Bosh sahifa> 2 - section Karusel ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='Slide2ensectioninfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': "<Bosh sahifa> 2 - section yozuvi va sarlavhasi ma'lumotlari",
            },
        ),
    ]
