# Generated by Django 4.0.1 on 2022-03-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(blank=True, max_length=15)),
                ('Logo', models.ImageField(upload_to='logo', verbose_name="LOGO : 178x117 o'lcham tavsiya etiladi")),
                ('info', models.TextField(verbose_name="Konpaniya haqida ma'lumot")),
            ],
            options={
                'verbose_name_plural': "Konpaniya ma'lumotlari va u haqida",
            },
        ),
    ]
