# Generated by Django 4.0.4 on 2022-04-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sectioninfor4'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioninfor4',
            name='asdasd',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
