# Generated by Django 4.0.4 on 2022-04-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_zaybal_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaybal_section',
            name='text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
