# Generated by Django 4.0.1 on 2022-03-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_companyinfo_company_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainpage_1section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name="Sarlavha ostidagi text '160 ta letter tavsiya etiladi")),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='#1 bilan yozilgan text')),
                ('imgbig', models.ImageField(upload_to='img', verbose_name="Yordamchi suratlar (PNG format va 232x232 o'lchamlar tavsiya etiladi)")),
            ],
            options={
                'verbose_name_plural': 'Bosh sahifa 1-section',
            },
        ),
    ]
