# Generated by Django 3.2.4 on 2022-03-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220309_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biz_Haqimizda_background_tagi2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.ImageField(upload_to='about2/')),
                ('text', models.CharField(max_length=40, verbose_name='Matn')),
                ('izoh', models.TextField(verbose_name='Izoh')),
            ],
            options={
                'verbose_name_plural': 'Biz haqimizda background tagi2',
            },
        ),
        migrations.RenameField(
            model_name='biz_haqimizda_background_tagi',
            old_name='desc',
            new_name='izoh',
        ),
        migrations.AlterField(
            model_name='biz_haqimizda_background_tagi',
            name='text',
            field=models.CharField(max_length=40, verbose_name='Matn'),
        ),
    ]
