# Generated by Django 4.0.4 on 2022-04-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_zaybal_section_iconcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaybal_section',
            name='desccc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zaybal_section',
            name='textt',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
