# Generated by Django 4.0.4 on 2022-04-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_sectioninfor4_asdasd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioninfor4',
            name='cardicon1',
            field=models.ImageField(blank=True, upload_to='icon'),
        ),
        migrations.AddField(
            model_name='sectioninfor4',
            name='desccard1',
            field=models.CharField(default=1, max_length=70, verbose_name='1- card matni'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectioninfor4',
            name='titlecard1',
            field=models.CharField(default=1, max_length=70, verbose_name='1- card sarlavhasi'),
            preserve_default=False,
        ),
    ]
