# Generated by Django 3.2.4 on 2022-03-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220312_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biz_haqimizda_background_tagi2',
            old_name='svg',
            new_name='rasm',
        ),
    ]
