# Generated by Django 3.2.4 on 2022-03-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_svg_biz_haqimizda_background_tagi2_rasm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biz_Haqimizda_asosiy_rasmlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm_521x651', models.ImageField(upload_to='about3/')),
                ('rasm2_250x250', models.ImageField(upload_to='about3/')),
                ('rasm3_250x250', models.ImageField(upload_to='about3/')),
                ('rasm4_250x250', models.ImageField(upload_to='about3/')),
            ],
        ),
    ]
