# Generated by Django 4.0.4 on 2022-04-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sectioninfor4_cardicon1_sectioninfor4_desccard1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioninfor4',
            name='cardicon2',
            field=models.ImageField(blank=True, upload_to='icon'),
        ),
        migrations.AddField(
            model_name='sectioninfor4',
            name='cardicon3',
            field=models.ImageField(blank=True, upload_to='icon'),
        ),
        migrations.AddField(
            model_name='sectioninfor4',
            name='cardicon4',
            field=models.ImageField(blank=True, upload_to='icon'),
        ),
        migrations.AddField(
            model_name='sectioninfor4',
            name='cardicon5',
            field=models.ImageField(blank=True, upload_to='icon'),
        ),
        migrations.AddField(
            model_name='sectioninfor4',
            name='desccard2',
            field=models.CharField(default=1, max_length=70, verbose_name='1-card matni'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectioninfor4',
            name='desccard3',
            field=models.CharField(default=1, max_length=70, verbose_name='1-card matni'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectioninfor4',
            name='desccard4',
            field=models.CharField(default=1, max_length=70, verbose_name='1-card matni'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectioninfor4',
            name='desccard5',
            field=models.CharField(default=1, max_length=70, verbose_name='1-card matni'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectioninfor4',
            name='titlecard2',
            field=models.CharField(default=1, max_length=70, verbose_name='1-card sarlavhasi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectioninfor4',
            name='titlecard3',
            field=models.CharField(default=1, max_length=70, verbose_name='1-card sarlavhasi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectioninfor4',
            name='titlecard4',
            field=models.CharField(default=1, max_length=70, verbose_name='1-card sarlavhasi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectioninfor4',
            name='titlecard5',
            field=models.CharField(default=1, max_length=70, verbose_name='1-card sarlavhasi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sectioninfor4',
            name='desccard1',
            field=models.CharField(max_length=70, verbose_name='1-card matni'),
        ),
        migrations.AlterField(
            model_name='sectioninfor4',
            name='titlecard1',
            field=models.CharField(max_length=70, verbose_name='1-card sarlavhasi'),
        ),
    ]
