# Generated by Django 4.0.4 on 2022-04-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_zaybal_section_desccc_zaybal_section_textt'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaybal_section',
            name='desccc2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zaybal_section',
            name='iconcard2',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zaybal_section',
            name='textt2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
