# Generated by Django 4.0.4 on 2022-04-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sectioninfor4_cardicon2_sectioninfor4_cardicon3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioninfor4',
            name='desccard2',
            field=models.CharField(max_length=70, verbose_name='2-card matni'),
        ),
        migrations.AlterField(
            model_name='sectioninfor4',
            name='desccard3',
            field=models.CharField(max_length=70, verbose_name='3-card matni'),
        ),
        migrations.AlterField(
            model_name='sectioninfor4',
            name='desccard4',
            field=models.CharField(max_length=70, verbose_name='4-card matni'),
        ),
        migrations.AlterField(
            model_name='sectioninfor4',
            name='desccard5',
            field=models.CharField(max_length=70, verbose_name='5-card matni'),
        ),
        migrations.AlterField(
            model_name='sectioninfor4',
            name='titlecard2',
            field=models.CharField(max_length=70, verbose_name='2-card sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='sectioninfor4',
            name='titlecard3',
            field=models.CharField(max_length=70, verbose_name='3-card sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='sectioninfor4',
            name='titlecard4',
            field=models.CharField(max_length=70, verbose_name='4-card sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='sectioninfor4',
            name='titlecard5',
            field=models.CharField(max_length=70, verbose_name='5-card sarlavhasi'),
        ),
    ]
