# Generated by Django 3.2.4 on 2022-03-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_biz_haqimizda_asosiy_rasmlari'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biz_haqimizda_asosiy_rasmlari',
            options={'verbose_name_plural': '03_Biz haqimizda asosiy rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='biz_haqimizda_background_tagi',
            options={'verbose_name_plural': '01_Biz haqimizda background tagi'},
        ),
        migrations.AlterModelOptions(
            name='biz_haqimizda_background_tagi2',
            options={'verbose_name_plural': '02_Biz haqimizda background tagi2'},
        ),
    ]
