# Generated by Django 4.0.1 on 2022-04-17 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_zaybal_section_desccc2_zaybal_section_iconcard2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section3s',
        ),
    ]
