# Generated by Django 4.0.4 on 2022-04-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_sectioninfor4_desccard2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectioninfor4',
            old_name='cardicon1',
            new_name='icon1',
        ),
        migrations.RenameField(
            model_name='sectioninfor4',
            old_name='cardicon2',
            new_name='icon2',
        ),
        migrations.RenameField(
            model_name='sectioninfor4',
            old_name='cardicon3',
            new_name='icon3',
        ),
        migrations.RenameField(
            model_name='sectioninfor4',
            old_name='cardicon4',
            new_name='icon4',
        ),
        migrations.RenameField(
            model_name='sectioninfor4',
            old_name='cardicon5',
            new_name='icon5',
        ),
    ]
