# Generated by Django 3.2.4 on 2022-03-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220312_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biz_Haqimizda_asosiy_rasm_matnlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavxa', models.CharField(max_length=40, verbose_name='Sarlavxa')),
                ('text', models.CharField(max_length=40, verbose_name='Matn')),
                ('izoh1', models.TextField(verbose_name='Izoh')),
                ('izoh2', models.TextField(verbose_name='Izoh')),
            ],
            options={
                'verbose_name_plural': '03_Biz haqimizda asosiy rasm matnlari',
            },
        ),
    ]
