# Generated by Django 4.0.4 on 2022-04-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sectioninfor6'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioninfor6',
            name='desc_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectioninfor6',
            name='desc_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectioninfor6',
            name='desc_3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectioninfor6',
            name='sarlavha_malumoti',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectioninfor6',
            name='sarlavha_texti',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
