# Generated by Django 3.2.4 on 2022-03-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_biz_haqimizda_asosiy_rasm_matnlari'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biz_haqimizda_asosiy_rasm_matnlari',
            options={'verbose_name_plural': '04_Biz haqimizda asosiy rasm matnlari'},
        ),
    ]
