# Generated by Django 4.0.4 on 2022-04-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_sectioninfor4_icon1_alter_sectioninfor4_icon2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioninfor4',
            name='icon1',
            field=models.ImageField(blank=True, upload_to='icon'),
        ),
        migrations.AlterField(
            model_name='sectioninfor4',
            name='icon2',
            field=models.ImageField(blank=True, upload_to='icon'),
        ),
        migrations.AlterField(
            model_name='sectioninfor4',
            name='icon3',
            field=models.ImageField(blank=True, upload_to='icon'),
        ),
        migrations.AlterField(
            model_name='sectioninfor4',
            name='icon4',
            field=models.ImageField(blank=True, upload_to='icon'),
        ),
        migrations.AlterField(
            model_name='sectioninfor4',
            name='icon5',
            field=models.ImageField(blank=True, upload_to='icon'),
        ),
    ]
