# Generated by Django 3.2.4 on 2022-03-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_biz_haqimizda_asosiy_rasm_matnlari_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biz_Haqimizda_statiskalar_tagi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavxa', models.CharField(max_length=40, verbose_name='Sarlavxa')),
                ('matn', models.CharField(max_length=40, verbose_name='Matn')),
                ('rasm_84x100', models.ImageField(upload_to='about5/')),
                ('rasm_matni', models.CharField(max_length=40, verbose_name='Matn')),
                ('rasm_izohi', models.TextField(verbose_name='Izoh')),
            ],
            options={
                'verbose_name_plural': '04_Biz haqimizda statiskalar tagi',
            },
        ),
    ]
