# Generated by Django 4.0.1 on 2022-04-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_sectioninfor4_icon1_alter_sectioninfor4_icon2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section3s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=70, verbose_name='3- section krish yozuvi')),
                ('title', models.CharField(max_length=70, verbose_name='3- section krish yozuvi osti')),
                ('cardicon1', models.ImageField(blank=True, upload_to='icon')),
                ('cardicon2', models.ImageField(blank=True, upload_to='icon')),
                ('titlecard1', models.CharField(max_length=70, verbose_name='1- card sarlavhasi')),
                ('desccard1', models.CharField(max_length=70, verbose_name='1- card matni')),
                ('titlecard2', models.CharField(max_length=70, verbose_name='2- card sarlavhasi')),
                ('desccard2', models.CharField(max_length=70, verbose_name='2- card matni')),
            ],
            options={
                'verbose_name_plural': "<Bosh sahifa> 3- Section ma'lumotlari ",
            },
        ),
    ]
