# Generated by Django 3.2.4 on 2022-03-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_biz_haqimizda_statiskalar_tagi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biz_haqimizda_statiskalar_tagi',
            options={'verbose_name_plural': '05_Biz haqimizda statiskalar tagi'},
        ),
    ]
