# Generated by Django 3.2.4 on 2022-03-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_biz_haqimizda_statiskalar_tagi_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biz_Haqimizda_pastdagi_asosiy_rasmlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm_305x350', models.ImageField(upload_to='about6/')),
                ('matn', models.CharField(max_length=30)),
                ('izoh', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '06_Biz haqimizda pastdagi asosiy rasmlar',
            },
        ),
    ]
