# Generated by Django 3.2.4 on 2022-03-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_biz_haqimizda_pastdagi_asosiy_rasmlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='biz_haqimizda_pastdagi_asosiy_rasmlar',
            name='asosit_izoh',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biz_haqimizda_pastdagi_asosiy_rasmlar',
            name='asosiy_matn',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
