# Generated by Django 3.2.4 on 2022-03-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220312_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biz_Haqimizda_pastdagi_asosiy_rasmlar_matni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asosiy_matn', models.CharField(max_length=20)),
                ('asosiy_izoh', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': '06_Biz haqimizda pastdagi asosiy rasmlar',
            },
        ),
        migrations.AlterModelOptions(
            name='biz_haqimizda_pastdagi_asosiy_rasmlar',
            options={'verbose_name_plural': '07_Biz haqimizda pastdagi asosiy rasmlar'},
        ),
        migrations.RemoveField(
            model_name='biz_haqimizda_pastdagi_asosiy_rasmlar',
            name='asosit_izoh',
        ),
        migrations.RemoveField(
            model_name='biz_haqimizda_pastdagi_asosiy_rasmlar',
            name='asosiy_matn',
        ),
    ]
