# Generated by Django 3.2.4 on 2022-03-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220312_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biz_haqimizda_pastdagi_asosiy_rasmlar_matni',
            options={'verbose_name_plural': '06_Biz haqimizda pastdagi asosiy rasmlar matni'},
        ),
    ]
