# Generated by Django 3.2.4 on 2022-03-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_biz_haqimizda_pastdagi_asosiy_rasmlar_matni_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='biz_haqimizda_pastdagi_asosiy_rasmlar',
            name='facebook_ssil',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
