# Generated by Django 3.2.4 on 2022-03-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_biz_haqimizda_pastdagi_asosiy_rasmlar_facebook_ssil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biz_haqimizda_pastdagi_asosiy_rasmlar',
            old_name='facebook_ssil',
            new_name='facebook_url',
        ),
        migrations.AddField(
            model_name='biz_haqimizda_pastdagi_asosiy_rasmlar',
            name='instagram_url',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biz_haqimizda_pastdagi_asosiy_rasmlar',
            name='telegram_url',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biz_haqimizda_pastdagi_asosiy_rasmlar',
            name='youtube_url',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
