# Generated by Django 4.0.1 on 2022-03-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mainpage_1section'),
        ('main', '0018_auto_20220312_2153'),
    ]

    operations = [
    ]
