# Generated by Django 4.0.1 on 2022-04-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_merge_0003_mainpage_1section_0018_auto_20220312_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide2ensectionCarusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='img')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': "Kompaniya ma'lumotlari va u haqida",
            },
        ),
        migrations.CreateModel(
            name='Slide2ensectioninfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name_plural': "Konpaniya ma'lumotlari va u haqida"},
        ),
    ]
