# Generated by Django 4.0.1 on 2022-04-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_mainpage_1section_title1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage_1section',
            name='title1',
            field=models.CharField(blank=True, max_length=70, verbose_name='Title'),
        ),
    ]
