# Generated by Django 4.0.4 on 2022-04-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_mainpage_1section_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage_1section',
            name='img2',
            field=models.ImageField(upload_to='img', verbose_name="Yordamchi suratlar2 (PNG format va 232x232 o'lchamlar tavsiya etiladi)"),
        ),
        migrations.AlterField(
            model_name='mainpage_1section',
            name='img3',
            field=models.ImageField(upload_to='img', verbose_name="Yordamchi suratlar3 (PNG format va 250x250 o'lchamlar tavsiya etiladi)"),
        ),
    ]
