# Generated by Django 4.0.1 on 2022-04-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_mainpage_1section_desc_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide2ensectioncarusel',
            name='icon',
        ),
    ]
