# Generated by Django 4.0.4 on 2022-04-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_mainpage_1section_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide2ensectioncarusel',
            name='icon',
        ),
        migrations.AlterField(
            model_name='mainpage_1section',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='#1 bilan yozilgan text'),
        ),
    ]
