# Generated by Django 4.0.4 on 2022-04-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_slide2ensectioncarusel_icon'),
        ('main', '0028_remove_slide2ensectioncarusel_icon_and_more'),
    ]

    operations = [
    ]
